name: "Continuos Integration"

on:
  pull_request:
    branches:
      - "main"
  workflow_dispatch:

jobs:
  continuous-integration:
    name: Checkout, lint and build
    timeout-minutes: 10
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.16.1]

    steps:
      - name: Checkout files
        uses: actions/checkout@v4

      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: npm install

      - name: Run Lint
        run: npm run lint

      - name: Build project
        run: npm run build
